import "./globals.css";

import { Inter, Nunito } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { ReactQueryClientProvider } from "@/providers/ReactQueryClientProvider";

const inter = Inter({
  variable: "--font-inter",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ReactQueryClientProvider>
        <html lang="en" className="w-full">
          <body
            className={`${inter.variable} ${nunito.variable}  antialiased dark`}
            suppressHydrationWarning
            data-lt-installed
          >
            {children}
          </body>
        </html>
      </ReactQueryClientProvider>
    </ClerkProvider>
  );
}
